# 线性模型

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import  datasets,linear_model,discriminant_analysis, cross_validation

C:\ProgramData\Anaconda3\envs\python3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
def load_data():
    diabetes = datasets.load_diabetes()
    return cross_validation.train_test_split(diabetes.data,diabetes.target,test_size=0.25,random_state=0)

In [3]:
X_train,X_test,y_train,y_test =load_data()

# 1、线性回归模型

In [4]:
print("线性回归模型：linear_model.LinearRegression")
regr = linear_model.LinearRegression()
regr.fit(X_train,y_train)
print('Coefficients:%s'% (regr.coef_))
print("Intercept ：%.2f"% regr.intercept_)
print("Residual sum of squares: %.2f" % np.mean((regr.predict(X_test) - y_test)**2))
print("Score :%.2f" %regr.score(X_test,y_test))

线性回归模型：linear_model.LinearRegression
Coefficients:[ -43.26774487 -208.67053951  593.39797213  302.89814903 -560.27689824
  261.47657106   -8.83343952  135.93715156  703.22658427   28.34844354]
Intercept ：153.07
Residual sum of squares: 3180.20
Score :0.36


# 2、线性回归模型的正则化
## 2.1、岭回归（RIdge Regression）

In [5]:
regr = linear_model.Ridge()
regr.fit(X_train,y_train)
print('Coefficients:%s'% (regr.coef_))
print("Intercept ：%.2f"% regr.intercept_)
print("Residual sum of squares: %.2f" % np.mean((regr.predict(X_test) - y_test)**2))
print("Score :%.2f" %regr.score(X_test,y_test))

Coefficients:[  21.19927911  -60.47711393  302.87575204  179.41206395    8.90911449
  -28.8080548  -149.30722541  112.67185758  250.53760873   99.57749017]
Intercept ：152.45
Residual sum of squares: 3192.33
Score :0.36


## 2.2 Lasso回归

In [6]:
regr = linear_model.Lasso()
regr.fit(X_train,y_train)
print('Coefficients:%s'% (regr.coef_))
print("Intercept ：%.2f"% regr.intercept_)
print("Residual sum of squares: %.2f" % np.mean((regr.predict(X_test) - y_test)**2))
print("Score :%.2f" %regr.score(X_test,y_test))

Coefficients:[   0.           -0.          442.67992538    0.            0.            0.
   -0.            0.          330.76014648    0.        ]
Intercept ：152.52
Residual sum of squares: 3583.42
Score :0.28


## 2.3 ElasticNet 回归

In [7]:
regr = linear_model.ElasticNet()
regr.fit(X_train,y_train)
print('Coefficients:%s'% (regr.coef_))
print("Intercept ：%.2f"% regr.intercept_)
print("Residual sum of squares: %.2f" % np.mean((regr.predict(X_test) - y_test)**2))
print("Score :%.2f" %regr.score(X_test,y_test))

Coefficients:[ 0.40560736  0.          3.76542456  2.38531508  0.58677945  0.22891647
 -2.15858149  2.33867566  3.49846121  1.98299707]
Intercept ：151.93
Residual sum of squares: 4922.36
Score :0.01


# 3 逻辑回归

In [13]:
def load_data():
    iris = datasets.load_iris()
    X_train = iris.data
    y_train = iris.target
    return cross_validation.train_test_split(X_train,y_train,test_size=0.25,random_state=0,stratify=y_train)
X_train,X_test,y_train,y_test =load_data()

In [9]:
regr = linear_model.LogisticRegression()
regr.fit(X_train,y_train)
print('Coefficients:%s'% (regr.coef_))
print("Intercept ：%s"% regr.intercept_)
print("Residual sum of squares: %.2f" % np.mean((regr.predict(X_test) - y_test)**2))
print("Score :%.2f" %regr.score(X_test,y_test))

Coefficients:[[ 0.39310895  1.35470406 -2.12308303 -0.96477916]
 [ 0.22462128 -1.34888898  0.60067997 -1.24122398]
 [-1.50918214 -1.29436177  2.14150484  2.2961458 ]]
Intercept ：[ 0.24122458  1.13775782 -1.09418724]
Residual sum of squares: 0.03
Score :0.97


In [10]:
regr = linear_model.LogisticRegression(multi_class='multinomial',solver='lbfgs')
regr.fit(X_train,y_train)
print('Coefficients:%s'% (regr.coef_))
print("Intercept ：%s"% regr.intercept_)
print("Residual sum of squares: %.2f" % np.mean((regr.predict(X_test) - y_test)**2))
print("Score :%.2f" %regr.score(X_test,y_test))

Coefficients:[[-0.38365872  0.85501328 -2.27224244 -0.98486171]
 [ 0.34359409 -0.37367647 -0.03043553 -0.86135577]
 [ 0.04006464 -0.48133681  2.30267797  1.84621747]]
Intercept ：[  8.79984878   2.46853199 -11.26838077]
Residual sum of squares: 0.00
Score :1.00


# 4、线性判别分析

In [11]:
regr = discriminant_analysis.LinearDiscriminantAnalysis()
regr.fit(X_train,y_train)
print('Coefficients:%s'% (regr.coef_))
print("Intercept ：%s"% regr.intercept_)
print("Residual sum of squares: %.2f" % np.mean((regr.predict(X_test) - y_test)**2))
print("Score :%.2f" %regr.score(X_test,y_test))

Coefficients:[[  6.575853     9.75807593 -14.34026669 -21.39076537]
 [ -1.98385061  -3.49791089   4.21495042   2.60304299]
 [ -4.47116022  -6.09542385   9.85886057  18.29330864]]
Intercept ：[-15.33097142   0.46730077 -30.53297367]
Residual sum of squares: 0.00
Score :1.00
